# Generated by Django 5.1.1 on 2024-11-19 13:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myan', '0002_album_remove_playlist_image_remove_playlist_songs_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='plays',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='song',
            name='audio_file',
            field=models.FileField(upload_to='songs/'),
        ),
        migrations.AlterField(
            model_name='song',
            name='playlist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myan.playlist'),
        ),
    ]
