# Generated by Django 5.1.1 on 2024-11-20 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myan', '0003_song_plays_alter_song_audio_file_alter_song_playlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='audio_file',
            field=models.FileField(default='songs/default.mp3', upload_to='songs/'),
        ),
    ]
